# Travis CI configuration file for deploying to GitHub Pages

# Specify the environment
group: container
dist: jammy  # Use Ubuntu 22.04 (Jammy Jellyfish)
language: generic  # No specific language required for this build

# Install any dependencies if needed
install:
  - echo "No dependencies to install"

# Deployment configuration
deploy:
  provider: pages
  skip_cleanup: true  # Ensures the build directory isn't cleaned up before deployment
  github_token: $GITHUB_TOKEN  # GitHub personal access token stored in Travis CI settings as an environment variable
  keep_history: true  # Keep commit history for the gh-pages branch
  local_dir: docs  # Specify the directory to deploy (matches your GitHub Pages /docs setting)
  on:
    branch: main  # Deploy only when changes are pushed to the main branch
  verbose: true  # Enable verbose output for easier debugging

# Optional script to build the site before deployment
script:
  - echo "Building the site (if necessary)"

# Optionally clean up files before the build starts
before_install:
  - echo "Starting Travis CI build"
