language: java

jobs:
  include:
    - name: "Ubuntu Bionic (18.04) with OpenJDK 21"
      dist: bionic
      jdk: openjdk21
      before_install:
        - echo "[BIONIC] JAVA_HOME = $JAVA_HOME"
        - java -version || echo "Failed to run java -version"

    - name: "Ubuntu Focal (20.04) with OpenJDK 21"
      dist: focal
      jdk: openjdk21
      before_install:
        - echo "[FOCAL] JAVA_HOME = $JAVA_HOME"
        - java -version || echo "Failed to run java -version"

    - name: "Ubuntu Jammy (22.04) with OpenJDK 21"
      dist: jammy
      jdk: openjdk21
      before_install:
        - echo "[JAMMY] JAVA_HOME = $JAVA_HOME"
        - java -version || echo "Failed to run java -version"
