os: linux
node_js: node
language: node_js
dist: focal
script:
  - echo "Testing deployment with dpl" > index.html
cache:
  directories:
    - node_modules
group: stable
addons:
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "."
  target_branch: gh-pages
  token: "$GITHUB_TOKEN"
on:
  branch:
    - feat/travis
    - main
