os: linux
node_js: node
language: node_js
dist: focal
script:
- ".bin/create-index.sh"
cache:
directories:
- node_modules
group: stable
addons:
deploy:
- provider: pages
strategy: git
skip_cleanup: true
local_dir: ".pages"
target_branch: gh-pages
'on':
branch:
- feat/travis
token: "$GITHUB_TOKEN"
url: github.com
