language: java
dist: focal
jdk:
  - openjdk17

install: skip
script: java -version

jobs:
  include:
    - dist: bionic
    - dist: xenial
    - dist: focal
    - dist: jammy
    - dist: bionic
      group: previous
    - dist: focal
      group: previous
    - dist: jammy
      group: previous
    - dist: xenial
      group: previous


