language: node_js
os:
  - linux
  - osx
dist: trusty
node_js:
  - 12.1.0

install:
  - npm install

stages:
  - name: Test
  - name: Integration tests
  - name: Build

jobs:
  include:
    - stage: Test
      os: osx
      osx_image: xcode14.2
      before_script:
        - export FIREFOX_BIN=$(which firefox)
      script:
        - npm run test:all

    - stage: Test
      os: linux
      addons:
        chrome: stable
        firefox: latest
      script:
        - npm run test:all

    - stage: Integration tests
      script:
        - echo "Running integration tests" # Placeholder for actual integration test script

    - stage: Build
      script:
        - echo "Running build process" # Placeholder for actual build script
