stages:
  - Test

jobs:
  include:
    - stage: Test
      os: osx
      osx_image: xcode14.2
      addons:
        chrome: stable
        firefox: latest
      env:
        - BROWSERS=ChromeHeadless,Firefox
        - MOZ_HEADLESS=1

    - stage: Test
      os: linux
      dist: bionic
      before_script:
        - sh -e /etc/init.d/xvfb start
      addons:
        chrome: stable
        firefox: latest
      env:
        - BROWSERS=Chrome,Firefox
        - MOZ_HEADLESS=1

global:
  - MOZ_HEADLESS=1
